import os.path
Import('env')
Import('chip')

test_env = env

test_lib = test_env.StaticLibrary(target='demos_mock', source=['mock_memio.cpp'])
common_tests = Split(
        'fake_board.cpp memio_test.cpp memio_mock_test.cpp '
        'peripheral_test.cpp syscontrol_test.cpp nvic_test.cpp ')

common_tests_objs = [test_env.Object(t) for t in common_tests]

chip_test_objs = test_env.Object(Glob('%s_*_test.cpp' % chip.lower()))
run_chip_tests = test_env.Program(
        LIBS='demos_%s_native' % chip,
        target='run_%s_tests' % chip,
        source=['test_runner.cpp'] + chip_test_objs + common_tests_objs + test_lib)

Return('test_lib')
