"""
    Copyright 2018 Google LLC

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

import os.path
Import('env')
Import('chip')

test_env = env

test_lib = test_env.StaticLibrary(target='demos_mock', source=['mock_memio.cpp', 'freertos_mock.cpp', 'stub_helper.cc'])
common_tests = Split(
        'memio_test.cpp memio_mock_test.cpp freertos_mock_test.cpp stub_helper_test.cc '
        'peripheral_test.cpp syscontrol_test.cpp nvic_test.cpp os_init_test.cpp systick_test.cpp')

common_tests_objs = [test_env.Object(t) for t in common_tests]

chip_test_extras = []
chip_test_objs = []

if env['BUILD_CHIP_TESTS']:
    chip_test_extras = test_env.Object(Glob('%s_*_fake.cpp' % chip.lower()))
    chip_test_objs = test_env.Object(Glob('%s_*_test.cpp' % chip.lower()))

run_chip_tests = test_env.Program(
        LIBS='demos_native',
        target='run_all_tests',
        source=['test_runner.cpp'] + chip_test_objs + common_tests_objs + test_lib + chip_test_extras)

Return('test_lib')
